name: "cade.site"
description: "Cade Brown's personal blog"
author: Cade Brown
author_name: Cade Brown
author_email: brown.cade@gmail.com

url: '' 
baseurl: ''

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

excerpt_separator: <!--more-->

plugins:
  - jekyll-paginate
  - jekyll-feed

paginate: 10
paginate_path: /page-:num
permalink: /:title

source: .
destination: ./_site

sass:
  style: :compressed
  sass_dir: assets/css/
